language: python
sudo: false
os:
  - linux
cache:
  pip: true
python:
  # - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
install:
  - pip install coveralls
  - pip install .[dev]
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - flake8 .
  - py.test --cov=mesa tests/
  - black . --check --exclude=/cookiecutter
after_success:
  - coveralls
